[package]
name = "minimal-elf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-layout = "4.0.2"
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
